import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { after, before, describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CLI = path.join(ROOT, "bin/cli.mjs");

// The regression these tests exist for: `add` must never write AGENTS.md.
//
// The kit compiles its rules into four files, one of which is named AGENTS.md.
// That is also the conventional name for a repository's own agent contract —
// tritonai-website has one, tracked, 18 KB, and its CONTRIBUTING.md says in as
// many words not to copy the kit's over it. An install that clobbered it would
// replace a specific contract with a generic one and report success.
const CONTRACT = "AGENTS.md";

let workdir;

async function run(args, options = {}) {
  try {
    const { stdout, stderr } = await execFileAsync(process.execPath, [CLI, ...args], {
      cwd: options.cwd ?? workdir,
      env: { ...process.env, npm_config_yes: "true" },
    });
    return { code: 0, stdout, stderr };
  } catch (error) {
    return { code: error.code ?? 1, stdout: error.stdout ?? "", stderr: error.stderr ?? "" };
  }
}

const exists = (target) => stat(target).then(() => true).catch(() => false);

before(async () => {
  workdir = await mkdtemp(path.join(tmpdir(), "decorator-kit-test-"));
});

after(async () => {
  await rm(workdir, { recursive: true, force: true });
});

describe("add", () => {
  it("never writes AGENTS.md into a project that has one", async () => {
    const project = path.join(workdir, "has-contract");
    await mkdir(project, { recursive: true });
    const ours = "# This repository's own agent contract\n\nDo not overwrite me.\n";
    await writeFile(path.join(project, CONTRACT), ours);

    const result = await run(["add"], { cwd: project });
    assert.equal(result.code, 0);

    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), ours);
    assert.match(result.stdout, /refused\s+AGENTS\.md/);
  });

  it("never writes AGENTS.md even when the project does not have one", async () => {
    // The dangerous case a "don't overwrite existing files" guard would miss:
    // tritonai-website has no CLAUDE.md and no .cursorrules, so a guard keyed on
    // existence would happily create both — and a repo whose contract is
    // AGENTS.md would end up with two competing rule sets at its root.
    const project = path.join(workdir, "no-contract");
    await mkdir(project, { recursive: true });

    const result = await run(["add"], { cwd: project });
    assert.equal(result.code, 0);

    assert.equal(await exists(path.join(project, CONTRACT)), false);
    assert.equal(await exists(path.join(project, "CLAUDE.md")), true);
  });

  it("refuses AGENTS.md under --force too", async () => {
    const project = path.join(workdir, "forced");
    await mkdir(project, { recursive: true });
    const ours = "# Mine\n";
    await writeFile(path.join(project, CONTRACT), ours);

    const result = await run(["add", "--force"], { cwd: project });
    assert.equal(result.code, 0);
    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), ours);
  });

  it("omits AGENTS.md from the manifest, so sync can never reach it", async () => {
    const project = path.join(workdir, "manifest");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    const manifest = JSON.parse(await readFile(path.join(project, "decorator-kit.json"), "utf8"));
    assert.ok(!manifest.manages.includes(CONTRACT));
    assert.ok(manifest.manages.includes("CLAUDE.md"));
    assert.ok(manifest.manages.includes(".claude/skills/ucsd-decorator"));

    // Even if AGENTS.md appears later, sync operates on the manifest only.
    await writeFile(path.join(project, CONTRACT), "# Added afterwards\n");
    await run(["sync"], { cwd: project });
    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), "# Added afterwards\n");
  });

  it("writes the tool rule files and publishes the skill", async () => {
    const project = path.join(workdir, "installed");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    for (const file of ["CLAUDE.md", ".cursorrules", ".github/copilot-instructions.md"]) {
      assert.equal(await exists(path.join(project, file)), true, `${file} should exist`);
    }
    assert.equal(await exists(path.join(project, ".claude/skills/ucsd-decorator/SKILL.md")), true);

    const claude = await readFile(path.join(project, "CLAUDE.md"), "utf8");
    assert.match(claude, /Generated by ucsd-decorator-kit@/);
    // The resolution order must name the package that actually exists.
    assert.match(claude, /node_modules\/ucsd-decorator-v5\/dist/);
    assert.doesNotMatch(claude, /@ucsd\/decorator/);
  });

  it("does not touch package.json or CI without being asked", async () => {
    const project = path.join(workdir, "untouched");
    await mkdir(project, { recursive: true });
    const original = JSON.stringify({ name: "existing", version: "1.0.0" }, null, 2);
    await writeFile(path.join(project, "package.json"), original);

    await run(["add"], { cwd: project });

    assert.equal(await readFile(path.join(project, "package.json"), "utf8"), original);
    assert.equal(await exists(path.join(project, ".github/dependabot.yml")), false);
    assert.equal(await exists(path.join(project, ".github/workflows/decorator.yml")), false);
  });
});

describe("sync", () => {
  it("refreshes AGENTS.md when the manifest says it is managed (the init shape)", async () => {
    // `add` never puts AGENTS.md in the manifest, so build that shape directly
    // rather than paying for a real `init`, which installs real npm packages.
    const project = path.join(workdir, "init-shape");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    const manifestPath = path.join(project, "decorator-kit.json");
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    manifest.manages.push(CONTRACT);
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2));
    await writeFile(path.join(project, CONTRACT), "# stale\n");

    const result = await run(["sync"], { cwd: project });
    assert.equal(result.code, 0);
    assert.match(result.stdout, /wrote\s+AGENTS\.md/);

    const agents = await readFile(path.join(project, CONTRACT), "utf8");
    assert.match(agents, /Generated by ucsd-decorator-kit@/);
    assert.doesNotMatch(agents, /# stale/);
  });
});

describe("init", () => {
  it("refuses to run in a directory that already looks like a project", async () => {
    const project = path.join(workdir, "existing-project");
    await mkdir(path.join(project, "src"), { recursive: true });

    const result = await run(["init"], { cwd: project });
    assert.equal(result.code, 1);
    assert.match(result.stderr, /already looks like a project/);
    assert.match(result.stderr, /ucsd-decorator-kit add/);
    // It must bail before writing anything at all.
    assert.equal(await exists(path.join(project, "CLAUDE.md")), false);
    assert.equal(await exists(path.join(project, CONTRACT)), false);
  });
});

describe("check", () => {
  it("passes after add, fails once a managed file is edited, passes after sync", async () => {
    const project = path.join(workdir, "drifted");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    assert.equal((await run(["check"], { cwd: project })).code, 0);

    const claude = path.join(project, "CLAUDE.md");
    await writeFile(claude, `${await readFile(claude, "utf8")}\nlocal edit\n`);

    const failed = await run(["check"], { cwd: project });
    assert.equal(failed.code, 1);
    assert.match(failed.stderr, /CLAUDE\.md/);

    await run(["sync"], { cwd: project });
    assert.equal((await run(["check"], { cwd: project })).code, 0);
  });

  it("notices a stale published skill", async () => {
    const project = path.join(workdir, "stale-skill");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    await rm(path.join(project, ".claude/skills/ucsd-decorator/references/security.md"));

    const failed = await run(["check"], { cwd: project });
    assert.equal(failed.code, 1);
    assert.match(failed.stderr, /skills\/ucsd-decorator/);
  });

  it("errors when the project was never set up", async () => {
    const project = path.join(workdir, "never-added");
    await mkdir(project, { recursive: true });

    const result = await run(["check"], { cwd: project });
    assert.equal(result.code, 1);
    assert.match(result.stderr, /decorator-kit\.json/);
  });
});
