import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdtemp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { after, before, describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { decoratorPage } from "./fixtures/decorator-page.mjs";

const execFileAsync = promisify(execFile);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CLI = path.join(ROOT, "bin/cli.mjs");

// The regression these tests exist for: `add` must never write AGENTS.md.
//
// The kit compiles its rules into four files, one of which is named AGENTS.md.
// That is also the conventional name for a repository's own agent contract —
// tritonai-website has one, tracked, 18 KB, and its CONTRIBUTING.md says in as
// many words not to copy the kit's over it. An install that clobbered it would
// replace a specific contract with a generic one and report success.
const CONTRACT = "AGENTS.md";

let workdir;

async function run(args, options = {}) {
  try {
    const { stdout, stderr } = await execFileAsync(process.execPath, [CLI, ...args], {
      cwd: options.cwd ?? workdir,
      env: { ...process.env, npm_config_yes: "true" },
    });
    return { code: 0, stdout, stderr };
  } catch (error) {
    return { code: error.code ?? 1, stdout: error.stdout ?? "", stderr: error.stderr ?? "" };
  }
}

const exists = (target) => stat(target).then(() => true).catch(() => false);

before(async () => {
  workdir = await mkdtemp(path.join(tmpdir(), "decorator-kit-test-"));
});

after(async () => {
  await rm(workdir, { recursive: true, force: true });
});

describe("add", () => {
  it("never writes AGENTS.md into a project that has one", async () => {
    const project = path.join(workdir, "has-contract");
    await mkdir(project, { recursive: true });
    const ours = "# This repository's own agent contract\n\nDo not overwrite me.\n";
    await writeFile(path.join(project, CONTRACT), ours);

    const result = await run(["add"], { cwd: project });
    assert.equal(result.code, 0);

    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), ours);
    assert.match(result.stdout, /refused\s+AGENTS\.md/);
  });

  it("never writes AGENTS.md even when the project does not have one", async () => {
    // The dangerous case a "don't overwrite existing files" guard would miss:
    // tritonai-website has no CLAUDE.md and no .cursorrules, so a guard keyed on
    // existence would happily create both — and a repo whose contract is
    // AGENTS.md would end up with two competing rule sets at its root.
    const project = path.join(workdir, "no-contract");
    await mkdir(project, { recursive: true });

    const result = await run(["add"], { cwd: project });
    assert.equal(result.code, 0);

    assert.equal(await exists(path.join(project, CONTRACT)), false);
    assert.equal(await exists(path.join(project, "CLAUDE.md")), true);
  });

  it("refuses AGENTS.md under --force too", async () => {
    const project = path.join(workdir, "forced");
    await mkdir(project, { recursive: true });
    const ours = "# Mine\n";
    await writeFile(path.join(project, CONTRACT), ours);

    const result = await run(["add", "--force"], { cwd: project });
    assert.equal(result.code, 0);
    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), ours);
  });

  it("omits AGENTS.md from the manifest, so sync can never reach it", async () => {
    const project = path.join(workdir, "manifest");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    const manifest = JSON.parse(await readFile(path.join(project, "decorator-kit.json"), "utf8"));
    assert.ok(!manifest.manages.includes(CONTRACT));
    assert.ok(manifest.manages.includes("CLAUDE.md"));
    assert.ok(manifest.manages.includes(".claude/skills/ucsd-decorator"));

    // Even if AGENTS.md appears later, sync operates on the manifest only.
    await writeFile(path.join(project, CONTRACT), "# Added afterwards\n");
    await run(["sync"], { cwd: project });
    assert.equal(await readFile(path.join(project, CONTRACT), "utf8"), "# Added afterwards\n");
  });

  it("writes the tool rule files and publishes the skill", async () => {
    const project = path.join(workdir, "installed");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    for (const file of ["CLAUDE.md", ".cursorrules", ".github/copilot-instructions.md"]) {
      assert.equal(await exists(path.join(project, file)), true, `${file} should exist`);
    }
    assert.equal(await exists(path.join(project, ".claude/skills/ucsd-decorator/SKILL.md")), true);

    const claude = await readFile(path.join(project, "CLAUDE.md"), "utf8");
    assert.match(claude, /Generated by ucsd-decorator-kit@/);
    // The resolution order must name the package that actually exists.
    assert.match(claude, /node_modules\/ucsd-decorator-v5\/dist/);
    assert.doesNotMatch(claude, /@ucsd\/decorator/);
  });

  it("does not touch package.json or CI without being asked", async () => {
    const project = path.join(workdir, "untouched");
    await mkdir(project, { recursive: true });
    const original = JSON.stringify({ name: "existing", version: "1.0.0" }, null, 2);
    await writeFile(path.join(project, "package.json"), original);

    await run(["add"], { cwd: project });

    assert.equal(await readFile(path.join(project, "package.json"), "utf8"), original);
    assert.equal(await exists(path.join(project, ".github/dependabot.yml")), false);
    assert.equal(await exists(path.join(project, ".github/workflows/decorator.yml")), false);
    assert.equal(await exists(path.join(project, ".claude/settings.json")), false);
  });
});

describe("add --with-hook", () => {
  it("writes a fresh .claude/settings.json with the Stop hook", async () => {
    const project = path.join(workdir, "hook-fresh");
    await mkdir(project, { recursive: true });

    const result = await run(["add", "--with-hook"], { cwd: project });
    assert.equal(result.code, 0);

    const settings = JSON.parse(await readFile(path.join(project, ".claude/settings.json"), "utf8"));
    assert.equal(settings.hooks.Stop.length, 1);
    const command = settings.hooks.Stop[0].hooks[0].command;
    assert.match(command, /ucsd-decorator-kit verify/);
    assert.equal(settings.hooks.Stop[0].hooks[0].asyncRewake, true, "must background, not block the turn");
  });

  it("merges into an existing settings.json without disturbing unrelated content", async () => {
    const project = path.join(workdir, "hook-merge");
    await mkdir(path.join(project, ".claude"), { recursive: true });
    const original = {
      permissions: { allow: ["Bash(npm *)"] },
      hooks: { PostToolUse: [{ matcher: "Write|Edit", hooks: [{ type: "command", command: "prettier --write" }] }] },
    };
    await writeFile(path.join(project, ".claude/settings.json"), JSON.stringify(original, null, 2));

    const result = await run(["add", "--with-hook"], { cwd: project });
    assert.equal(result.code, 0);

    const settings = JSON.parse(await readFile(path.join(project, ".claude/settings.json"), "utf8"));
    assert.deepEqual(settings.permissions.allow, original.permissions.allow, "unrelated permissions preserved");
    assert.deepEqual(settings.hooks.PostToolUse, original.hooks.PostToolUse, "unrelated hook preserved");
    assert.equal(settings.hooks.Stop.length, 1, "the chrome gate hook was added alongside it");
  });

  it("also merges permission guards for the chrome *.local.json files and --accept", async () => {
    const project = path.join(workdir, "hook-permissions");
    await mkdir(project, { recursive: true });

    const result = await run(["add", "--with-hook"], { cwd: project });
    assert.equal(result.code, 0);

    const settings = JSON.parse(await readFile(path.join(project, ".claude/settings.json"), "utf8"));
    assert.ok(settings.permissions.deny.includes("Edit(chrome-styling.local.json)"));
    assert.ok(settings.permissions.deny.includes("Write(chrome-contract.local.json)"));
    assert.ok(settings.permissions.ask.includes("Bash(*--accept*)"));
  });

  it("is idempotent — running it twice does not duplicate the hook or permission rules", async () => {
    const project = path.join(workdir, "hook-idempotent");
    await mkdir(project, { recursive: true });

    await run(["add", "--with-hook"], { cwd: project });
    const second = await run(["add", "--with-hook"], { cwd: project });
    assert.equal(second.code, 0);
    assert.match(second.stdout, /already present/);

    const settings = JSON.parse(await readFile(path.join(project, ".claude/settings.json"), "utf8"));
    assert.equal(settings.hooks.Stop.length, 1);
    assert.equal(settings.permissions.deny.filter((rule) => rule === "Write(chrome-contract.local.json)").length, 1);
    assert.equal(settings.permissions.ask.filter((rule) => rule === "Bash(*--accept*)").length, 1);
  });

  it("is not installed by plain `add`, only under the flag", async () => {
    const project = path.join(workdir, "hook-opt-in");
    await mkdir(project, { recursive: true });

    const result = await run(["add"], { cwd: project });
    assert.equal(result.code, 0);
    assert.equal(await exists(path.join(project, ".claude/settings.json")), false);
    assert.match(result.stdout, /add --with-hook/);
  });

  it("fails clearly on a malformed existing settings.json rather than overwriting it", async () => {
    const project = path.join(workdir, "hook-malformed");
    await mkdir(path.join(project, ".claude"), { recursive: true });
    await writeFile(path.join(project, ".claude/settings.json"), "{ not valid json");

    const result = await run(["add", "--with-hook"], { cwd: project });
    assert.equal(result.code, 1);
    assert.match(result.stderr, /settings\.json is not valid JSON/);
    assert.equal(await readFile(path.join(project, ".claude/settings.json"), "utf8"), "{ not valid json");
  });
});

describe("sync", () => {
  it("refreshes AGENTS.md when the manifest says it is managed (the init shape)", async () => {
    // `add` never puts AGENTS.md in the manifest, so build that shape directly
    // rather than paying for a real `init`, which installs real npm packages.
    const project = path.join(workdir, "init-shape");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    const manifestPath = path.join(project, "decorator-kit.json");
    const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
    manifest.manages.push(CONTRACT);
    await writeFile(manifestPath, JSON.stringify(manifest, null, 2));
    await writeFile(path.join(project, CONTRACT), "# stale\n");

    const result = await run(["sync"], { cwd: project });
    assert.equal(result.code, 0);
    assert.match(result.stdout, /wrote\s+AGENTS\.md/);

    const agents = await readFile(path.join(project, CONTRACT), "utf8");
    assert.match(agents, /Generated by ucsd-decorator-kit@/);
    assert.doesNotMatch(agents, /# stale/);
  });
});

describe("init", () => {
  it("refuses to run in a directory that already looks like a project", async () => {
    const project = path.join(workdir, "existing-project");
    await mkdir(path.join(project, "src"), { recursive: true });

    const result = await run(["init"], { cwd: project });
    assert.equal(result.code, 1);
    assert.match(result.stderr, /already looks like a project/);
    assert.match(result.stderr, /ucsd-decorator-kit add/);
    // It must bail before writing anything at all.
    assert.equal(await exists(path.join(project, "CLAUDE.md")), false);
    assert.equal(await exists(path.join(project, CONTRACT)), false);
  });
});

describe("check", () => {
  it("passes after add, fails once a managed file is edited, passes after sync", async () => {
    const project = path.join(workdir, "drifted");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    assert.equal((await run(["check"], { cwd: project })).code, 0);

    const claude = path.join(project, "CLAUDE.md");
    await writeFile(claude, `${await readFile(claude, "utf8")}\nlocal edit\n`);

    const failed = await run(["check"], { cwd: project });
    assert.equal(failed.code, 1);
    assert.match(failed.stderr, /CLAUDE\.md/);

    await run(["sync"], { cwd: project });
    assert.equal((await run(["check"], { cwd: project })).code, 0);
  });

  it("notices a stale published skill", async () => {
    const project = path.join(workdir, "stale-skill");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project });

    await rm(path.join(project, ".claude/skills/ucsd-decorator/references/security.md"));

    const failed = await run(["check"], { cwd: project });
    assert.equal(failed.code, 1);
    assert.match(failed.stderr, /skills\/ucsd-decorator/);
  });

  it("errors when the project was never set up", async () => {
    const project = path.join(workdir, "never-added");
    await mkdir(project, { recursive: true });

    const result = await run(["check"], { cwd: project });
    assert.equal(result.code, 1);
    assert.match(result.stderr, /decorator-kit\.json/);
  });
});

// `verify` is a thin execFileSync wrapper around checks/chrome-contract.mjs —
// exercised directly and thoroughly in test/chrome-contract.test.mjs. These
// tests are about the wrapper itself: flag passthrough, exit-code
// propagation, and that it stays a distinct command from `check` (rule-file
// staleness) rather than colliding with it.
describe("verify", () => {
  it("passes flags through to checks/chrome-contract.mjs and propagates its exit code", async () => {
    const project = path.join(workdir, "verify-flow");
    await mkdir(project, { recursive: true });
    await writeFile(path.join(project, "index.html"), decoratorPage("Home"));
    await writeFile(path.join(project, "about.html"), decoratorPage("About"));

    const explained = await run(["verify", "--explain"], { cwd: project });
    assert.equal(explained.code, 0);
    assert.match(explained.stdout, /canvas: main#main-content/);

    const before = await run(["verify"], { cwd: project }); // default: --check
    assert.equal(before.code, 1);
    assert.match(before.stderr, /chrome\/golden/);

    const accepted = await run(["verify", "--accept", "--reason", "initial baseline", "--yes"], { cwd: project });
    assert.equal(accepted.code, 0);
    assert.equal(await exists(path.join(project, "chrome-contract.local.json")), true);

    const after = await run(["verify"], { cwd: project });
    assert.equal(after.code, 0);
    assert.match(after.stdout, /all four tiers pass/);
  });

  it("is a different command from `check` — one is rule-file staleness, the other is this project's own chrome", async () => {
    const project = path.join(workdir, "verify-vs-check");
    await mkdir(project, { recursive: true });
    await run(["add"], { cwd: project }); // makes `check` (rule-file staleness) pass
    await writeFile(path.join(project, "index.html"), decoratorPage("Home"));

    const checked = await run(["check"], { cwd: project });
    assert.equal(checked.code, 0, "rule files are current — check has nothing to do with page markup");

    const verified = await run(["verify"], { cwd: project });
    assert.equal(verified.code, 1, "the page's chrome has never been accepted — verify is a different question");
  });
});
