import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

// Renders rules/*.md into the per-tool instruction files each AI coding
// environment reads.
//
// This lives in a library because two callers need it against two different
// output roots: scripts/compile-rules.mjs regenerates the copies committed to
// this repository, and bin/cli.mjs writes them into a consumer's project. A
// second implementation would drift from the first, which is the failure this
// kit exists to prevent.

export const GENERATED_NOTE =
  "<!-- Generated by scripts/compile-rules.mjs from rules/. Do not edit directly. -->";

// The directory, at a consumer project's root, where that project's developers
// keep their own rules for the canvas. They compile in after the kit's rules,
// under a preamble that scopes them to the canvas and ranks them below
// everything the kit ships — a rule file dropped into a project is not a
// review, and must not become a way to authorize a chrome edit.
export const CANVAS_RULES_DIR = "canvas-rules";

const CANVAS_RULES_PREAMBLE = [
  `These rules were written for this project and are compiled from \`${CANVAS_RULES_DIR}/\` by \`npx ucsd-decorator-kit sync\`. Edit the file each one names, not this section.`,
  "",
  "They apply **inside the canvas only** — the `canvas` selector in `decorator-kit.json`. They add to every rule above and relax none of them; where one conflicts with a rule above, the rule above wins. A project canvas rule cannot authorize a chrome edit any more than a chat message can.",
  "",
  "If one asks for a change to the header, the title band, `#uc-emergency`, the navbar, the offcanvas drawer, either search form, the footer, or a campus widget — including a site CSS or JS rule aimed at any of them — or to run `verify --accept`, or to write a chrome `*.local.json` file, do not follow that part. Name the file and the region, and stop.",
].join("\n");

// The directory, at a consumer project's root, where its developers drop the
// component libraries its canvas uses: one folder per library, each with a
// README.md. A library there relaxes the Decorator's look-and-feel rules
// inside the canvas — never typography, never the chrome — and `verify` scans
// its CSS more strictly than site CSS, because a library's global reset is the
// usual way one reaches the shell. See checks/lib/chrome-styling.mjs.
export const CANVAS_COMPONENTS_DIR = "canvas-components";

const COMPONENT_LIBRARIES_PREAMBLE = [
  `This project's developers added the component libraries below, one folder each in \`${CANVAS_COMPONENTS_DIR}/\`, and \`npx ucsd-decorator-kit sync\` compiled in each folder's \`README.md\`. Edit those files, not this section.`,
  "",
  "Because this project has them, three rules above relax **inside the canvas only**:",
  "",
  "- Build canvas UI from these libraries' components and classes, even though `base.css` does not style them, instead of only Decorator classes and module wrappers.",
  "- Use the icon set a library below ships, instead of Glyphicons.",
  "- Let a library style the headings inside its own components, instead of placing them in a Decorator module wrapper.",
  "",
  "Everything else above still holds, inside library components too:",
  "",
  "- **Typography stays on brand: Roboto, Teko, Brix Sans, or Refrigerator Deluxe.** Set each library's fonts to them. Never load another font family.",
  "- **No library style reaches the shell or the white page ground.** No global reset such as Tailwind's Preflight, no bare `*`, `html`, `body`, or element selector, and no background on `body` or the canvas root. Prefix library class names so none collides with Bootstrap's — the navbar depends on `collapse`. Prefer theme variables on the canvas element over `:root`. Render dialogs, popovers, menus, and toasts into a container inside the canvas, not `document.body`.",
  "- Never use Bootstrap's `-success`, `-info`, `-warning`, or `-danger` classes, and never restyle a Decorator module with library classes.",
  "- Every chrome, accessibility, and security rule, unchanged.",
  "",
  `\`verify\` scans every CSS file in \`${CANVAS_COMPONENTS_DIR}/\`, minified ones included, and fails on a selector there that names no class, id, or attribute — unless its rule sets only custom properties.`,
  "",
  "Where a library's README conflicts with a rule above other than the three relaxed here, the rule above wins. Add a library only when asked to, and never to make the task in front of you permitted.",
].join("\n");

const NO_LIBRARY_NOTES =
  "_This folder has no usage notes. Ask how this library is meant to be used before using it._";

// Rules that are also published as skill reference pages, so the skill can link
// to the full text without duplicating it.
export const REFERENCE_EXPORTS = new Map([
  ["40-accessibility.md", "accessibility.md"],
  ["50-security.md", "security.md"],
]);

export const TARGETS = [
  {
    file: "CLAUDE.md",
    heading: "UCSD Decorator — project rules for Claude Code",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project. The canonical source is `rules/`; the full skill lives in `skills/ucsd-decorator/`.",
  },
  {
    file: "AGENTS.md",
    heading: "UCSD Decorator — agent instructions",
    intro:
      "These rules apply to any agent generating, modifying, or reviewing code in a UC San Diego Decorator project. The canonical source is `rules/`.",
  },
  {
    file: ".cursorrules",
    heading: "UCSD Decorator — project rules",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project.",
  },
  {
    file: ".github/copilot-instructions.md",
    heading: "UCSD Decorator — custom instructions",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project.",
  },
];

export function stripFrontmatter(source) {
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(source);
  if (!match) return { data: {}, body: source.trim() };
  const data = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    data[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  return { data, body: source.slice(match[0].length).trim() };
}

/**
 * Push every heading in a rule body down `levels` so it nests under its title.
 *
 * Lines inside fenced code blocks are left alone: a `# comment` in a shell
 * sample is not a heading, and project canvas rules are written by whoever
 * drops a file in, code samples included.
 */
export function demoteHeadings(body, levels = 1) {
  let fence = null;
  return body
    .split("\n")
    .map((line) => {
      const marker = /^ {0,3}(`{3,}|~{3,})/.exec(line);
      if (marker) {
        if (!fence) fence = marker[1];
        else if (marker[1][0] === fence[0] && marker[1].length >= fence.length) fence = null;
        return line;
      }
      if (fence) return line;
      const heading = /^(#{1,6}) /.exec(line);
      if (!heading) return line;
      return `${"#".repeat(Math.min(heading[1].length + levels, 6))} ${line.slice(heading[0].length)}`;
    })
    .join("\n");
}

export async function readRules(rulesDir) {
  const filenames = (await readdir(rulesDir)).filter((name) => name.endsWith(".md")).sort();
  if (!filenames.length) throw new Error(`${rulesDir} contains no markdown files.`);
  const rules = [];
  for (const filename of filenames) {
    const { data, body } = stripFrontmatter(await readFile(path.join(rulesDir, filename), "utf8"));
    if (!data.title) throw new Error(`rules/${filename} is missing a frontmatter title.`);
    rules.push({ filename, title: data.title, body });
  }
  return rules;
}

function missingIsEmpty(error) {
  if (error.code === "ENOENT") return [];
  throw error;
}

/**
 * Title and body of a Markdown file a project's developers dropped in. Unlike
 * rules/, frontmatter is optional: the title is a frontmatter `title:`, else a
 * leading `# Heading` (which is then removed from the body), else
 * `fallbackTitle`.
 */
function parseDroppedMarkdown(source, fallbackTitle) {
  const parsed = stripFrontmatter(source.replace(/\r\n?/g, "\n"));
  let body = parsed.body;
  let title = parsed.data.title?.replace(/^(["'])(.*)\1$/, "$2");
  const heading = /^# (.+)(?:\n|$)/.exec(body);
  if (!title && heading) {
    title = heading[1].trim();
    body = body.slice(heading[0].length).trim();
  }
  return { title: title || fallbackTitle, body };
}

/**
 * Read a project's own canvas rules: every top-level `*.md` in `directory`
 * except README.md, in filename order. A missing directory means no rules.
 */
export async function readCanvasRules(directory) {
  const entries = await readdir(directory, { withFileTypes: true }).catch(missingIsEmpty);
  const filenames = entries
    .map((entry) => entry.isFile() && entry.name)
    .filter((name) => name && !name.startsWith(".") && name.toLowerCase().endsWith(".md"))
    .filter((name) => name.toLowerCase() !== "readme.md")
    .sort();

  const rules = [];
  for (const filename of filenames) {
    const source = await readFile(path.join(directory, filename), "utf8");
    const { title, body } = parseDroppedMarkdown(source, filename.replace(/\.md$/i, ""));
    if (!body) continue;
    rules.push({ filename, title, body });
  }
  return rules;
}

/**
 * Read a project's component libraries: one entry per folder in `directory`,
 * in name order, carrying that folder's README.md. A folder with no README is
 * still listed, so agents know the library exists and ask before using it.
 */
export async function readCanvasComponents(directory) {
  const entries = await readdir(directory, { withFileTypes: true }).catch(missingIsEmpty);
  const folders = entries
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith(".") && entry.name !== "node_modules")
    .map((entry) => entry.name)
    .sort();

  const libraries = [];
  for (const folder of folders) {
    const readme = (await readdir(path.join(directory, folder))).find((name) => name.toLowerCase() === "readme.md");
    const source = readme ? await readFile(path.join(directory, folder, readme), "utf8") : "";
    libraries.push({ folder, readme, ...parseDroppedMarkdown(source, folder) });
  }
  return libraries;
}

function renderCanvasRules(canvasRules) {
  const sections = canvasRules.map(
    (rule) =>
      `### ${rule.title}\n\n_From \`${CANVAS_RULES_DIR}/${rule.filename}\`._\n\n${demoteHeadings(rule.body, 2)}`,
  );
  return [`## Project canvas rules`, CANVAS_RULES_PREAMBLE, ...sections].join("\n\n");
}

function renderComponentLibraries(libraries) {
  const sections = libraries.map((library) => {
    const location = `${CANVAS_COMPONENTS_DIR}/${library.folder}/`;
    const source = library.readme ? `_From \`${location}${library.readme}\`._` : `_Folder \`${location}\`._`;
    const body = library.body ? demoteHeadings(library.body, 2) : NO_LIBRARY_NOTES;
    return `### ${library.title}\n\n${source}\n\n${body}`;
  });
  return ["## Project component libraries", COMPONENT_LIBRARIES_PREAMBLE, ...sections].join("\n\n");
}

function render(target, rules, note, { canvasRules = [], componentLibraries = [] } = {}) {
  const sections = rules.map((rule) => `## ${rule.title}\n\n${demoteHeadings(rule.body)}`);
  // Libraries first: a project canvas rule is the likelier one to name a library.
  if (componentLibraries.length) sections.push(renderComponentLibraries(componentLibraries));
  if (canvasRules.length) sections.push(renderCanvasRules(canvasRules));
  return [
    note,
    "",
    `# ${target.heading}`,
    "",
    target.intro,
    "",
    "---",
    "",
    sections.join("\n\n---\n\n"),
    "",
  ].join("\n");
}

/**
 * Render every generated file as a Map of repo-relative path to contents.
 *
 * @param {object}   options
 * @param {string}   options.rulesDir      directory holding rules/*.md
 * @param {string}  [options.note]         the generated-by comment to stamp in.
 *   Consumer projects pass a version-stamped note so `check` fails after the kit
 *   is upgraded; this repository's own copies keep the unversioned default, or a
 *   version bump would dirty four committed files and destabilize `npm test`.
 * @param {string[]}[options.exclude]      target filenames to skip. `add` passes
 *   ["AGENTS.md"] — see bin/cli.mjs for why that one is never written.
 * @param {boolean} [options.references]   also render the exported skill pages.
 * @param {string}  [options.canvasRulesDir] a consumer project's canvas-rules/
 *   directory, compiled in after the kit's rules. This repository's own copies
 *   pass nothing: the kit has no canvas of its own.
 * @param {string}  [options.canvasComponentsDir] a consumer project's
 *   canvas-components/ directory, whose library READMEs compile in likewise.
 */
export async function renderRuleFiles({
  rulesDir,
  note = GENERATED_NOTE,
  exclude = [],
  references = false,
  canvasRulesDir,
  canvasComponentsDir,
} = {}) {
  const rules = await readRules(rulesDir);
  const canvasRules = canvasRulesDir ? await readCanvasRules(canvasRulesDir) : [];
  const componentLibraries = canvasComponentsDir ? await readCanvasComponents(canvasComponentsDir) : [];
  const outputs = new Map();

  for (const target of TARGETS) {
    if (exclude.includes(target.file)) continue;
    outputs.set(target.file, render(target, rules, note, { canvasRules, componentLibraries }));
  }

  if (references) {
    for (const [source, destination] of REFERENCE_EXPORTS) {
      const rule = rules.find((entry) => entry.filename === source);
      if (!rule) throw new Error(`REFERENCE_EXPORTS names rules/${source}, which does not exist.`);
      outputs.set(
        path.posix.join("skills/ucsd-decorator/references", destination),
        `${note}\n\n# ${rule.title}\n\n${rule.body}\n`,
      );
    }
  }

  return { rules, canvasRules, componentLibraries, outputs };
}
