import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Compiles rules/*.md into the per-tool instruction files each AI coding
// environment reads, plus the two reference pages the skill links to.
//
// The Antigravity Code Kit maintained CLAUDE.md, .cursorrules, and
// .github/copilot-instructions.md as three hand-synced copies of the same text
// (17100 / 17090 / 17090 bytes). They drift. Generate them instead.
//
//   node scripts/compile-rules.mjs
//   node scripts/compile-rules.mjs --check    verify committed output is current

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RULES_DIR = path.join(ROOT, "rules");
const REFERENCES_DIR = path.join(ROOT, "skills/ucsd-decorator/references");

const GENERATED_NOTE =
  "<!-- Generated by scripts/compile-rules.mjs from rules/. Do not edit directly. -->";

// Rules that are also published as skill reference pages, so the skill can link
// to the full text without duplicating it.
const REFERENCE_EXPORTS = new Map([
  ["40-accessibility.md", "accessibility.md"],
  ["50-security.md", "security.md"],
]);

const TARGETS = [
  {
    file: "CLAUDE.md",
    heading: "UCSD Decorator — project rules for Claude Code",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project. The canonical source is `rules/`; the full skill lives in `skills/ucsd-decorator/`.",
  },
  {
    file: "AGENTS.md",
    heading: "UCSD Decorator — agent instructions",
    intro:
      "These rules apply to any agent generating, modifying, or reviewing code in a UC San Diego Decorator project. The canonical source is `rules/`.",
  },
  {
    file: ".cursorrules",
    heading: "UCSD Decorator — project rules",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project.",
  },
  {
    file: ".github/copilot-instructions.md",
    heading: "UCSD Decorator — custom instructions",
    intro:
      "These rules apply when generating, modifying, or reviewing code in a UC San Diego Decorator project.",
  },
];

function stripFrontmatter(source) {
  const match = /^---\n([\s\S]*?)\n---\n?/.exec(source);
  if (!match) return { data: {}, body: source.trim() };
  const data = {};
  for (const line of match[1].split("\n")) {
    const separator = line.indexOf(":");
    if (separator === -1) continue;
    data[line.slice(0, separator).trim()] = line.slice(separator + 1).trim();
  }
  return { data, body: source.slice(match[0].length).trim() };
}

/** Push every heading in a rule body down one level so it nests under its title. */
function demoteHeadings(body) {
  return body.replace(/^(#{1,5}) /gm, (_, hashes) => `${hashes}# `);
}

async function readRules() {
  const filenames = (await readdir(RULES_DIR)).filter((name) => name.endsWith(".md")).sort();
  if (!filenames.length) throw new Error("rules/ contains no markdown files.");
  const rules = [];
  for (const filename of filenames) {
    const { data, body } = stripFrontmatter(await readFile(path.join(RULES_DIR, filename), "utf8"));
    if (!data.title) throw new Error(`rules/${filename} is missing a frontmatter title.`);
    rules.push({ filename, title: data.title, body });
  }
  return rules;
}

function render(target, rules) {
  const sections = rules.map((rule) => `## ${rule.title}\n\n${demoteHeadings(rule.body)}`);
  return [
    GENERATED_NOTE,
    "",
    `# ${target.heading}`,
    "",
    target.intro,
    "",
    "---",
    "",
    sections.join("\n\n---\n\n"),
    "",
  ].join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  const rules = await readRules();
  const outputs = new Map();

  for (const target of TARGETS) outputs.set(target.file, render(target, rules));

  for (const [source, destination] of REFERENCE_EXPORTS) {
    const rule = rules.find((entry) => entry.filename === source);
    if (!rule) throw new Error(`REFERENCE_EXPORTS names rules/${source}, which does not exist.`);
    outputs.set(
      path.posix.join("skills/ucsd-decorator/references", destination),
      `${GENERATED_NOTE}\n\n# ${rule.title}\n\n${rule.body}\n`,
    );
  }

  const stale = [];
  for (const [relative, contents] of outputs) {
    const absolute = path.join(ROOT, relative);
    const current = await readFile(absolute, "utf8").catch(() => null);
    if (current === contents) continue;
    if (check) {
      stale.push(relative);
      continue;
    }
    await mkdir(path.dirname(absolute), { recursive: true });
    await writeFile(absolute, contents);
    console.log(`wrote ${relative}`);
  }

  if (check) {
    if (stale.length) {
      console.error(`These generated files are out of date with rules/:\n  ${stale.join("\n  ")}`);
      console.error("Run `node scripts/compile-rules.mjs` and commit the result.");
      process.exitCode = 1;
      return;
    }
    console.log(`All ${outputs.size} generated files are current with ${rules.length} rules.`);
    return;
  }
  console.log(`Compiled ${rules.length} rules into ${outputs.size} files.`);
}

await main();
